### ISSUE TITLE
Anroid: retrieveCalendars is returning an empty list

### ISSUE THREAD

**Issue by dbrpci** [builttoroam/flutter_plugins#560]
**Describe the bug**
On Android 14, retrieveCalendars is returning an empty list for me. I'm seeing this with the example app as well as in our own app that was previously working in the past.

**To Reproduce**
1. Open example app
2. Grant calendar permission
3. See empty screen

**Expected behavior**
It should return a list of calendars on the device

**Screenshots**
n/a

**Device(s) tested**
Pixel 9 Emulator, Android API 35
Pixel 8 Emulator, Android API 34
Pixel 6 device, Android v14

**Flutter doctor**
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.7 23H124 darwin-arm64, locale
    en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.0)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.93.1)
```

**Additional context**
```
  device_calendar:
    dependency: "direct main"
    description:
      name: device_calendar
      sha256: "683fb93ec302b6a65c0ce57df40ff9dcc2404f59c67a2f8b93e59318c8a0a225"
      url: "https://pub.dev"
    source: hosted
    version: "4.3.3"
    ```
